services:
  ollama:
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    volumes:
      - ./ollama:/root/.ollama
    pull_policy: always
    ports:
      - ${OLLAMA_PORT-11434}:11434
    tty: true
    environment:
      KEEP_ALIVE: -1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-all}
              capabilities:
                - gpu

  open-webui:
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      WEBUI_SECRET_KEY:
    restart: unless-stopped
